# Generated by Django 4.2.11 on 2024-03-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='company',
        ),
    ]
